apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-app
  labels:
    name: nginx-pv-app
spec:
  containers:
    - name: nginx-pv-app
      image: fedora/nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: my-persistent-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-persistent-volume
      persistentVolumeClaim:
        # 事前に定義した PVC 名を指定
        claimName: nginx-pvc
