apiVersion: v1
kind: Pod
metadata:
  name: secret-web-app-ssl
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - protocol: TCP
          containerPort: 443
      volumeMounts:
        - name: cert-volume
          mountPath: /etc/cert
  volumes:
    - name: cert-volume
      secret:
        secretName: www-cert
