apiVersion: v1
kind: Pod
metadata:
  name: secret-webapp
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
